export const FETCH_TICKERS = 'FETCH_TICKERS';
export const FETCH_TICKER = 'FETCH_TICKER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REFRESHED = 'REFRESHED';
